-- Oracle SQL for Oracle 12.C to create the GCD Database
CREATE USER GCD IDENTIFIED BY filenet;
GRANT SELECT on pending_trans$ TO GCD; 
GRANT SELECT on dba_2pc_pending TO GCD; 
GRANT SELECT on dba_pending_transactions TO GCD; 

GRANT SELECT on DUAL TO GCD; 
GRANT SELECT on product_component_version TO GCD; 
GRANT SELECT on USER_INDEXES TO GCD;
 
GRANT EXECUTE ON SYS.DBMS_SYSTEM TO GCD; 
GRANT EXECUTE ON SYS.DBMS_XA TO GCD; 
ALTER USER GCD QUOTA UNLIMITED ON USERS; 

GRANT CREATE TYPE TO GCD; 
GRANT CREATE VIEW TO GCD; 
GRANT CREATE TABLE TO GCD; 
GRANT CREATE CLUSTER TO GCD; 
GRANT CREATE SESSION TO GCD; 
GRANT CREATE TRIGGER TO GCD; 
GRANT CREATE SEQUENCE TO GCD; 
GRANT CREATE DIMENSION TO GCD; 
GRANT CREATE INDEXTYPE TO GCD; 
GRANT CREATE PROCEDURE TO GCD; 
GRANT CREATE MATERIALIZED VIEW TO GCD; 

alter user GCD account unlock;
